# Generated by Django 3.0.1 on 2020-01-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irisplants',
            name='species',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
