# Generated by Django 3.0.2 on 2020-01-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_irisplants_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irisplants',
            name='species',
            field=models.IntegerField(choices=[(0, 'Setosa'), (1, 'Versicolor'), (2, 'Virginica')]),
        ),
    ]
