# Generated by Django 3.0.2 on 2020-01-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisPlants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_petal', models.FloatField()),
                ('length_sepal', models.FloatField()),
                ('width_petal', models.FloatField()),
                ('width_sepal', models.FloatField()),
                ('species', models.IntegerField(choices=[(0, 'Setosa'), (1, 'Versicolor'), (2, 'Virginica')])),
            ],
        ),
    ]
